# Generated by Django 4.2.16 on 2024-10-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='current_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='target_word',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
